%+
% NAME:
%  synthwaveforms()
%
% VERSION:
%  $Id: synthwaveforms.m 2008-01-31 09:24 furche $
%
% AUTHOR:
%  J. Furche 
%
% DATE CREATED:
%  2008-01-31
%
% AIM:
%  Constructs synthetic waveforms based on real spikes in NEV-data
%
% DESCRIPTION:
% Constructs synthethic waveforms based on real spikes from the given
% Nev-file of a specified unit. N waveforms being subject to the same 
% distribution as the real data are generated by using the
% sample covariance-matrice as well as the sample mean.
% In order to use this function the matlabNEVLib10a has to be available.
% The data file has to be translated to a Matlab-structure using openNEV
% first.
%
% CATEGORY:
%  Statistics
%
% SYNTAX:
%* [mu,Waveforms,kurven,index]=synthwaveforms(Nevdatei,channel,unita,number)
%
% INPUTS:
%   Nevdatei:: Name of the translated Nev-file element in Matlab
%   channel:: list of electrodes 
%   unita:: list of units, the same length as the channellist.
%   number:: list containing the numbers of synthetic waveforms to be
%   generated for each channel/unit.
%
% OPTIONAL INPUTS:
%  --
%
% OUTPUTS:
% mu:: cell array of sample means for each channel/unit
% Waveforms:: cell array containing the real waveforms
% kurven:: cell array containing the synthetic waveforms
% index:: cell array containing the indices of the corresponding
% waveformspackets.
%
%
% PROCEDURE:
%  The function uses the underlying statistic (Covariance matrices and 
%  sample means) of the real waveforms to generate synthetic waves. Based
%  on cholesky factorization the synthetic waves are subject to the same
%  distribution.
%  
%
% EXAMPLE:
% Generate synthetic waveforms based on channel 54 unit 2 and channel 34
% unit 1 from the Nev-Object 'Neu'. 4000 and 580 waves shall be constructed
% respectively:
%* [mu,Waveforms,kurven,index]=synthwaveforms(Neu,[54,34],[2,1],[4000,580])
%
% SEE ALSO:
%  matlabNEVlib10a toolbox, 
%  <A>synthwaveformsplx<A/>
%
%-


function [mu,Waveforms,kurven,index]=synthwaveforms(Nevdatei,channel,unita,number)

if length(channel)~=length(unita) | length(channel)~=length(number)
    error('The length of channel,unita and number shall agree')
end


for i=1:length(channel) %each channel
        text=num2str(sprintf('electrode==%g & unit==%g',channel(i),unita(i)))
        [retVal, indices] = searchNEVByField(Nevdatei, text); 
        index{i}=find(retVal==1);
        Waveforms{i}=getPackets(Nevdatei,index{i},'waveform');
        Waveforms{i}(any(isnan(Waveforms{i})'),:) = [];
        mu{i}=1/length(index{i})*sum(Waveforms{i})
        [m,n]=size(Waveforms{i}');
        covi=cov(Waveforms{i});
        R=chol(covi);
        kurvesum=0;
        kurve=zeros(m,number(i));
        for j=1:number(i)
            tau=randn(m,1); 
            kurve(:,j)=R'*tau+mu{i}';
        end
        kurvesum=1/j*sum(kurve');
        figure(i)
        plot(kurve)
        hold on
        plot(kurvesum,'LineWidth',3)
        plot(mu{i},'r','LineWidth',2)
        hold off
        kurven{i}=kurve';
end
