%+
% NAME:
%  synthwaveformsplx()
%
% VERSION:
%  $Id: synthwaveformsplx.m 2008-02-13 09:24 furche $
%
% AUTHOR:
%  J. Furche 
%
% DATE CREATED:
%  2008-02-13
%
% AIM:
%  Constructs synthetic waveforms based on real spikes in plx-data
%
% DESCRIPTION:
% Constructs synthethic waveforms based on real spikes from the given
% Nev-file of a specified unit. N waveforms being subject to the same 
% distribution as the real data are generated by using the
% sample covariance-matrice as well as the sample mean.
% In order to use this function the toolbox 'ReadingPLXandDDTfilesinmatlab'
% has to be available 
% (loadable from 'http://www.plexoninc.com/support/softwaredevkit.html').
%
% CATEGORY:
%  Statistics
%
% SYNTAX:
%* [mu,Waveforms,kurven,index]=synthwaveformsfuerplx(plxdatei,channel,unita,number)
%
% INPUTS:
%   plxdatei:: name of the plx-file, the file has to be in current
%   directory
%   channel:: list of electrodes 
%   unita:: list of units, the same length as the channellist.
%   number:: list containing the numbers of synthetic waveforms to be
%   generated for each channel/unit.
%
% OPTIONAL INPUTS:
%  --
%
% OUTPUTS:
% mu:: cell array of sample means for each channel/unit
% Waveforms:: cell array containing the real waveforms
% kurven:: cell array containing the synthetic waveforms
%
%
% PROCEDURE:
%  The function uses the underlying statistic (Covariance matrices and 
%  sample means) of the real waveforms to generate synthetic waves. Based
%  on cholesky factorization the synthetic waves are subject to the same
%  distribution.
%  
%
% EXAMPLE:
% Generate synthetic waveforms based on channel 54 unit 2 and channel 34
% unit 1 from the plx-file 'experiment1'. 4000 and 580 waves shall be constructed
% respectively:
%* [mu,Waveforms,kurven]=synthwaveforms('experiment1.plx',[54,34],[2,1],[4000,580])
%
% SEE ALSO:
%  ReadingPLXandDDTfilesinmatlab toolbox 
%  (http://www.plexoninc.com/support/softwaredevkit.html), 
%  <A>synthwaveforms<A/>
%
%-

function [mu,Waveforms,kurven]=synthwaveformsplx(plxdatei,channel,unita,number)

if length(channel)~=length(unita) | length(channel)~=length(number)
    error('Pro Channel bitte genau eine Unit und eine Anzahl von künstlichen Waveform angeben')
end


for i=1:length(channel) %each Channel
        [n, npw, ts, wave] = plx_waves_v(plxdatei, channel(i), unita(i));
        Waveforms{i}=wave*1000;
        mu{i}=1/n*sum(Waveforms{i})
        [m,n]=size(Waveforms{i}');
        covi=cov(Waveforms{i});
        R=chol(covi);
        kurvesum=0;
        kurve=zeros(m,number(i));
        for j=1:number(i)
            tau=randn(m,1); 
            kurve(:,j)=R'*tau+mu{i}';
        end
        kurvesum=1/j*sum(kurve');
        figure(i)
        plot(kurve)
        hold on
        plot(kurvesum,'LineWidth',3)
        plot(mu{i},'r','LineWidth',2)
        hold off
        kurven{i}=kurve';
end
